## In order to quantize data, we have to decide how wide each bin should be. 

**The solution fall into two categories:**
    
    - fixed-width
    - adaptive

***Fixed-width binning*** - each bin contains a specific numeric range. The ranges can be custom designed or automatically segmented, and they can be linearly scaled or exponentially scaled.

In [1]:
# Import Numpy Library 

import numpy as np

In [3]:
#Generate 20 random integers uniformly between 0 to 99

small_counts= np.random.randint(0,100,20)
small_counts

array([58,  6, 52,  0, 70,  8, 27, 68, 81, 28, 39, 89, 16,  9, 81, 73, 98,
       76, 79, 39])

#### Using Division

In [4]:
# Map to evenly spaced bins 0-9 by division

np.floor_divide(small_counts, 10)

array([5, 0, 5, 0, 7, 0, 2, 6, 8, 2, 3, 8, 1, 0, 8, 7, 9, 7, 7, 3])

In [5]:
# An array of counts that span several magnitudes

large_counts = [296,8286, 64011, 80, 3, 725, 867, 2215, 7689, 11495, 91897,
               44, 28, 7971, 926, 122, 22222]

#### Using Log Function

In [6]:
# Map to exponential-width bins via the log function

np.floor(np.log10(large_counts))

array([2., 3., 4., 1., 0., 2., 2., 3., 3., 4., 4., 1., 1., 3., 2., 2., 4.])